services:
  - type: web
    name: panaderia-backend
    runtime: docker
    plan: free
    envVars:
      - key: APP_ENV
        value: production
      - key: ENABLE_DOCS
        value: "1"
      - key: LOG_LEVEL
        value: INFO
      - key: CORS_ORIGINS
        value: "*"
      - key: PORT
        value: "4000"
      - key: AUTH_REQUIRED
        value: "0"
      - key: DATABASE_URL
        sync: false
      - key: API_KEY
        sync: false
